-- Add authentication fields to users table
ALTER TABLE users ADD COLUMN email VARCHAR(255) NOT NULL UNIQUE AFTER name;
ALTER TABLE users ADD COLUMN password_hash VARCHAR(255) NOT NULL AFTER email;
ALTER TABLE users ADD COLUMN role ENUM('user', 'admin') DEFAULT 'user' AFTER password_hash;
ALTER TABLE users ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP AFTER role;
ALTER TABLE users ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;
