// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (name, dob)
VALUES (?, ?)
`

type CreateUserParams struct {
	Name string
	Dob  time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.Name, arg.Dob)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, name, dob FROM users WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Dob)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, dob FROM users ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Name, &i.Dob); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET name = ?, dob = ?
WHERE id = ?
`

type UpdateUserParams struct {
	Name string
	Dob  time.Time
	ID   int32
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser, arg.Name, arg.Dob, arg.ID)
	return err
}

const updateUserWithEmail = `-- name: UpdateUserWithEmail :exec
UPDATE users
SET name = ?, email = ?, dob = ?
WHERE id = ?
`

type UpdateUserWithEmailParams struct {
	Name  string
	Email string
	Dob   time.Time
	ID    int32
}

func (q *Queries) UpdateUserWithEmail(ctx context.Context, arg UpdateUserWithEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateUserWithEmail, arg.Name, arg.Email, arg.Dob, arg.ID)
	return err
}

const createUserWithAuth = `-- name: CreateUserWithAuth :exec
INSERT INTO users (name, email, password_hash, role, dob)
VALUES (?, ?, ?, ?, ?)
`

type CreateUserWithAuthParams struct {
	Name         string
	Email        string
	PasswordHash string
	Role         string
	Dob          time.Time
}

func (q *Queries) CreateUserWithAuth(ctx context.Context, arg CreateUserWithAuthParams) error {
	_, err := q.db.ExecContext(ctx, createUserWithAuth, arg.Name, arg.Email, arg.PasswordHash, arg.Role, arg.Dob)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, role, dob, created_at, updated_at FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(&i.ID, &i.Name, &i.Email, &i.PasswordHash, &i.Role, &i.Dob, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password_hash, role, dob, created_at, updated_at FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.Email, &i.PasswordHash, &i.Role, &i.Dob, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}
